Changed deprecated keys and used cryptosigner
in-toto/demo pull request #75
Opened 2024-05-17 06:14 UTC by DarikshaAnsari

"Fixed issues #73 , #74 , #67 , #68 "

changed in readme.md and run_demo.py
in-toto-run with --key is now --signing-key
in-toto-record with --key is now --signing-key
in-toto-verify with --layout-keys is now  --verification-keys

Used CryptoSigner instead of signer in create_layout.py and added module requirement in requirements.txt

2024-05-17 06:15 UTC, DarikshaAnsari commented
@lukpueh I have changed all the files you've mentioned , PTAL !!

2024-05-17 07:31 UTC, lukpueh requested changes
Thanks!! This is almost complete. Can you please check the [ci log](https://github.com/in-toto/demo/actions/runs/9123811857/job/25088867862?pr=75) and fix the errors? You can also run the test locally:
```sh
 python3 run_demo_md.py
```

I few hints:
- The functionary keys in `create_layout.py` (key_bob and key_carl) are no longer key dictionaries but `Key` objects now. You need to slightly adopt the way they are used in the rest of the script.
- If you do change the commands in `README.md`, you'll also need to update the expected output in `run_demo_md.py`. But you can also leave that for a separate PR, as we discussed.

2024-05-17 09:11 UTC, lukpueh commented on owner_alice/create_layout.py
> +    return key_dict
IMO it's okay to just import this internal method from in_toto:

```
# https://github.com/in-toto/in-toto/issues/663
from in_toto.models._signer import _load_public_key_from_file
```

2024-05-17 10:55 UTC, lukpueh commented
Hm. Tests are still failing. Feel free to debug, but this might be a bit tricky. I am happy to take over.

2024-05-21 08:25 UTC, lukpueh approved these changes
Nice troubleshooting with the keyid change!! Thanks

2024-05-21 08:25 UTC, merged

2024-05-21 08:30 UTC, DarikshaAnsari commented
Thank you @lukpueh working with this issue is so interesting.